### ISSUE TITLE
image == null!

### ISSUE THREAD

**Issue by fodorpapbalazs** [fodorpapbalazs/DP_Prototype#4]
Exception in thread "main" java.lang.IllegalArgumentException: image == null!
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1592)
	at javax.imageio.ImageIO.write(ImageIO.java:1520)
	at VideoProcessor.getFirstFrameFromMov(VideoProcessor.java:35)
	at Main.main(Main.java:16)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\fodorpapbalazs\Documents\GitHub\DP_Prototype\dpprototype\src\main\resources\mov\IMG_7568.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2018-04-01T18:43:23.000000Z
    com.apple.quicktime.location.ISO6709: +47.1878+018.4197+115.108/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 6 Plus
    com.apple.quicktime.software: 11.2.6
    com.apple.quicktime.creationdate: 2018-04-01T20:43:23+0200
  Duration: 00:00:10.94, start: 0.000000, bitrate: 15681 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 15577 kb/s, 29.98 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2018-04-01T18:43:23.000000Z
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2018-04-01T18:43:23.000000Z
      handler_name    : Core Media Data Handler
    Stream #0:2(und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2018-04-01T18:43:23.000000Z
      handler_name    : Core Media Data Handler
    Stream #0:3(und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2018-04-01T18:43:23.000000Z
      handler_name    : Core Media Data Handler

**Comment by fodorpapbalazs** [comment]
Issue solved wuth:
https://github.com/bytedeco/javacv/issues/116
